name: test-build-hook
on:
  push:
    branches:
      - stag
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: wget
      uses: wei/wget@v1
      with:
        args: ${{ secrets.JENKIN_URL }}/job/area-ci-cd-stag/build?token=${{ secrets.JENKIN_TOCKEN }}

